package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import compromissos2.connections.ConnectionFactory;
import compromissos2.Grupo;
import compromissos2.connections.UserConnection;
import compromissos2.Usuario;
import compromissos2.connections.GrupoConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class AddGrupo extends javax.swing.JFrame {

    static Usuario usuario;
    Connection conn;
    ConnectionFactory cf = new ConnectionFactory();
     static DefaultListModel demoList = new DefaultListModel();
    ArrayList<Usuario> lista = new ArrayList<>();

     
     static ArrayList<Usuario> listaContatosAdd = new ArrayList<>();
     static int IDZAO;
    
    public AddGrupo(Usuario usuario) {
        
        initComponents();
        
        this.usuario = usuario; 
             
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        
        // Foto Padrão 
        
        ArrayList<JTextField> campos = new ArrayList<>(Arrays.asList(
                textNome
        
        ));
        
       listaContatosAdd.clear();
        exibeContatos();
        
        btnAddContact.setOpaque(true);
        btnCriarGrupo.setOpaque(true);
        btnVoltar.setOpaque(true);
        
        btnAddContact.setBorderPainted(false);
        btnCriarGrupo.setBorderPainted(false);
        btnVoltar.setBorderPainted(false);
        
        /*
        
       
        // Iniciando os placeholders
        startPlaceHolders(campos);
    */
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboboxContatos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listContatos = new javax.swing.JList<>();
        btnAddContact = new javax.swing.JButton();
        textNome = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnCriarGrupo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescricao = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(203, 241, 245));
        jPanel1.setPreferredSize(new java.awt.Dimension(664, 540));

        comboboxContatos.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        comboboxContatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        comboboxContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxContatosActionPerformed(evt);
            }
        });

        listContatos.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        listContatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listContatos);

        btnAddContact.setBackground(new java.awt.Color(67, 154, 151));
        btnAddContact.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnAddContact.setForeground(new java.awt.Color(255, 255, 255));
        btnAddContact.setText("Add");
        btnAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddContactActionPerformed(evt);
            }
        });

        textNome.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        btnVoltar.setBackground(new java.awt.Color(67, 154, 151));
        btnVoltar.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnCriarGrupo.setBackground(new java.awt.Color(67, 154, 151));
        btnCriarGrupo.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        btnCriarGrupo.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarGrupo.setText("Criar Grupo");
        btnCriarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarGrupoActionPerformed(evt);
            }
        });

        textDescricao.setColumns(20);
        textDescricao.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        textDescricao.setRows(5);
        jScrollPane1.setViewportView(textDescricao);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 154, 151));
        jLabel1.setText("Adicionar Participantes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboboxContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddContact)
                        .addComponent(btnCriarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboboxContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddContact)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exibeContatos() {
    
         DefaultListModel model = new DefaultListModel();       
            ArrayList<Usuario> lista = carregaContatos(); 

            try {            
                int count = 0;
                while(lista.size() > count) {       
                    
                    listaContatosAdd.add(lista.get(count));
                    comboboxContatos.addItem(lista.get(count).getNome());               
                    count++;
                }                         
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null, "Erro em exibeContatos: " + ex);
            }
    }
    
    private ArrayList<Usuario> carregaContatos() {
    
        try {
            
            conn = cf.getConnection();
            conn.setAutoCommit(false);
            
            String query = "SELECT * FROM pessoa p WHERE p.id IN ( SELECT id_contato FROM pessoacontato pc WHERE pc.id_pessoa = ?)";

            int userId = Integer.valueOf(getId(usuario));
            PreparedStatement ps = conn.prepareStatement(query);  
            ps.setInt(1, userId);

            ResultSet rs = ps.executeQuery();                      

            while(rs.next()) {

                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd"); 
                Date date = formato.parse(rs.getString("data_nasc")); 

                Usuario contato = new Usuario(
                        rs.getString("nome"),
                        rs.getInt("id"),                 
                        date,
                        rs.getString("endereco"),
                        rs.getString("telefone"),
                        rs.getString("email")                      
                );
  
                lista.add(contato);      
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro em carregaContatos: " + ex);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro em carregaContatos: " + ex);
        }

        return lista;
    
    }
    
    public String getId(Usuario usuario) throws SQLException {

        UserConnection connection_usuario = new UserConnection(); 

        ResultSet rsUsuario = connection_usuario.autenticacao(usuario);           
        String idUsuario = "";

        if(rsUsuario.next()) 
            idUsuario = rsUsuario.getString("id");
        else 
            JOptionPane.showMessageDialog(null, "Problema ao estabelecer conexão com o usuário");

        return idUsuario;
    } 
    
    private void btnCriarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarGrupoActionPerformed
        
        try {
            
            String nome, descricao;
            
            nome = textNome.getText();
            descricao = textDescricao.getText();
            
            
            Grupo grupo = new Grupo(
                    nome,
                    descricao
            );
            
            InsereGrupoBanco(grupo);
            InsereContatosGrupo(grupo);
            
            this.dispose();
            new Home(usuario).setVisible(true);

        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnCriarGrupoActionPerformed

   private void InsereContatosGrupo(Grupo grupo) {
   
        ArrayList<Integer> contatosIds = new ArrayList<Integer>();
                    
        for(int i = 0; i < listaContatosAdd.size(); i++) {   
            
            for(int j = 0; j < listContatos.getModel().getSize(); j++) {
                
                if( ( listaContatosAdd.get(i).getNome() ).equals( listContatos.getModel().getElementAt(j)) )         
                    contatosIds.add( (listaContatosAdd.get(i).getId()) );           
            }              
        }
        
        System.out.println("Lista dos IDS : " + listaContatosAdd); 
        InsereGruposBanco(grupo, contatosIds);

   }
    
   private void InsereGruposBanco(Grupo grupo,  ArrayList<Integer> contatosIds) {
       
            
        try {    
            
            String query = "INSERT INTO pessoagrupo() VALUES(?, ?)";
            
            ConnectionFactory cf = new ConnectionFactory();
            conn = cf.getConnection();
            conn.setAutoCommit(false);
            
            PreparedStatement ps;

            ps = conn.prepareStatement(query);
            
            for(int i = 0; i < contatosIds.size(); i++) {
                
                
                ps.setInt(1, contatosIds.get(i));
                ps.setInt(2, IDZAO );
                
                System.out.println("ID: " + contatosIds.get(i));

                ps.execute();
                
  
            }
            
            conn.commit();
            ps.close();
            
    }catch(SQLException ex) {
            System.out.println(ex);
    }
       
       
       
   
   
   }
    
    private void comboboxContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxContatosActionPerformed

    }//GEN-LAST:event_comboboxContatosActionPerformed

    private void btnAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContactActionPerformed

        demoList.addElement(comboboxContatos.getSelectedItem());
        comboboxContatos.removeItem(comboboxContatos.getSelectedItem());
        listContatos.setModel(demoList);

    }//GEN-LAST:event_btnAddContactActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        new Home(usuario).setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void InsereGrupoBanco(Grupo grupo) {
        
        String query = "insert into grupo() values(?, ?, ?)";
        PreparedStatement ps;
        
        try {
            ConnectionFactory cf = new ConnectionFactory();
            conn = cf.getConnection();
            conn.setAutoCommit(false);
            
            ps = conn.prepareStatement(query);
            
            ps.setString(1, null);
            ps.setString(2, grupo.getNome());
            ps.setString(3, grupo.getDescricao());
            
            ps.execute();
            conn.commit();
            ps.close();
            
            ConectaGrupo(grupo);
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro em InsereGrupoBanco: " + ex.getMessage());
        }      
    }
    
     public void ConectaGrupo(Grupo grupo) {
          
        try {   
            
            // Conexão com usuário desta conta
           
            UserConnection connection_usuario = new UserConnection();   
            GrupoConnection connection_group = new GrupoConnection();   
            
            System.out.println("Usuario: " + usuario );
            System.out.println("Grupo: " + grupo);
            
            
            ResultSet rsUsuario = connection_usuario.autenticacao(usuario);           
            ResultSet rsGrupo = connection_group.autenticacao(grupo);           
           
            String idUsuario = "", idGrupo = "";
            
            if(rsUsuario.next()) 
                idUsuario = rsUsuario.getString("id");
            else 
                JOptionPane.showMessageDialog(null, "Problema ao estabelecer conexão com o usuário");
            
            if(rsGrupo.next()) {
                idGrupo = rsGrupo.getString("id");
                IDZAO = Integer.parseInt(idGrupo); 
            } else 
                 JOptionPane.showMessageDialog(null, "Problema ao estabelecer conexão com o grupo");
            
             
            
            
            // ID USUÁRIO E ID CONTATO
            String query = "insert into pessoagrupo() values(?, ?)";
            
        // Conexão com banco
            ConnectionFactory cf = new ConnectionFactory();
            conn = cf.getConnection();
            conn.setAutoCommit(false);
            
            PreparedStatement ps = conn.prepareStatement(query);  
                 
            ps.setInt(1, Integer.parseInt(idUsuario));
            ps.setInt(2, Integer.parseInt(idGrupo));
            
     
            ps.execute();
            conn.commit();
            ps.close();
             
            JOptionPane.showMessageDialog(null, "Grupo adicionado com sucesso!");
             
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());          
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGrupo(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddContact;
    private javax.swing.JButton btnCriarGrupo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboboxContatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listContatos;
    private javax.swing.JTextArea textDescricao;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
